#
# External API clients
#
# External meaning external for our infrastructure, which will always need to use the proxy/host
# that is present to be able to access outside resources
#
parameters:
  env(EXTERNAL_CACHE_DISABLE): false
  env(PROXY_HOST): null
  env(PROXY_PORT): null
  stream_context_allow_all:
    ssl:
      allow_self_signed: true
      verify_peer: false
      verify_peer_name: false

services:
  _defaults:
    public: true

  _instanceof:
    ExEss\Cms\ExternalAPI\AbstractSoapClientService:
      tags: ['client.soap']
